In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'A':[1,2],'B':[3,4]})

In [3]:
df2 = pd.DataFrame({'A':[5,6],'B':[7,8]})

In [4]:
pd.concat([df1,df2])

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [5]:
pd.concat([df1,df2],axis = 1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [6]:
df3 = pd.DataFrame({'id':[1,2,3],'name':['Alice','Bob','Charlie']})

In [7]:
df4 = pd.DataFrame({'id':[2,3,4],'score':[85,92,78]})

In [8]:
pd.merge(df3,df4,on = 'id')

   id     name  score
0   2      Bob     85
1   3  Charlie     92

In [9]:
pd.merge(df3,df4,on = 'id',how = 'left')

   id     name  score
0   1    Alice    NaN
1   2      Bob   85.0
2   3  Charlie   92.0

In [10]:
pd.merge(df3,df4,on = 'id',how = 'right')

   id     name  score
0   2      Bob     85
1   3  Charlie     92
2   4      NaN     78