In [1]:
import pandas as pd

In [2]:
data = {
    'Department':['Sales','Sales','IT','IT','HR','HR'],
    'Employee':['Alice','Bob','Charlie','David','Eve','Frank'],
    'Salary':[50000,60000,70000,80000,90000,45000],
    'Experience':[3,5,3,8,6,1]}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  Department Employee  Salary  Experience
0      Sales    Alice   50000           3
1      Sales      Bob   60000           5
2         IT  Charlie   70000           3
3         IT    David   80000           8
4         HR      Eve   90000           6
5         HR    Frank   45000           1

In [5]:
grouped = df.groupby('Department')

In [6]:
for name,group in grouped:
    print(name)
    print(group)

HR
  Department Employee  Salary  Experience
4         HR      Eve   90000           6
5         HR    Frank   45000           1
IT
  Department Employee  Salary  Experience
2         IT  Charlie   70000           3
3         IT    David   80000           8
Sales
  Department Employee  Salary  Experience
0      Sales    Alice   50000           3
1      Sales      Bob   60000           5

In [7]:
avg_sal = grouped['Salary'].mean()

In [8]:
avg_sal

Department
HR       67500.0
IT       75000.0
Sales    55000.0
Name: Salary, dtype: float64

In [9]:
sal_state = df.groupby('Department')['Salary'].agg(['mean','min','max','std'])

In [10]:
sal_state

               mean    min    max           std
Department
HR          67500.0  45000  90000  31819.805153
IT          75000.0  70000  80000   7071.067812
Sales       55000.0  50000  60000   7071.067812

In [11]:
res =grouped.agg({
    'Salary':['mean','sum'],
    'Experience':['mean','max','count']
})

In [12]:
res

             Salary         Experience
               mean     sum       mean max count
Department
HR          67500.0  135000        3.5   6     2
IT          75000.0  150000        5.5   8     2
Sales       55000.0  110000        4.0   5     2