In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', 
             '2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'Region': ['North', 'North', 'North', 'North', 
               'South', 'South', 'South', 'South'],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 120, 130, 180, 220, 140],
    'Quantity': [10, 15, 20, 12, 13, 18, 22, 14]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

         Date Region Product  Sales  Quantity
0  2023-01-01  North       A    100        10
1  2023-01-01  North       B    150        15
2  2023-01-02  North       A    200        20
3  2023-01-02  North       B    120        12
4  2023-01-01  South       A    130        13
5  2023-01-01  South       B    180        18
6  2023-01-02  South       A    220        22
7  2023-01-02  South       B    140        14

In [6]:
pivot1 = pd.pivot_table(df,values = 'Sales',index = 'Region',columns = 'Product',aggfunc='sum')

In [7]:
pivot1

Product    A    B
Region
North    300  270
South    350  320

In [8]:
pivot2 = pd.pivot_table(df,values = 'Sales' , index = ['Region','Product'] , columns = 'Date' , aggfunc = 'sum')

In [9]:
pivot2

Date            2023-01-01  2023-01-02
Region Product
North  A               100         200
       B               150         120
South  A               130         220
       B               180         140

In [10]:
pivot3 = pd.pivot_table(df, values= ['Sales','Quantity'], index = 'Region',columns = 'Product',aggfunc = 'sum')

In [11]:
pivot3

        Quantity     Sales
Product        A   B     A    B
Region
North         30  27   300  270
South         35  32   350  320

In [12]:
df_missing = df.copy()

In [13]:
df_missing.loc[0,'Sales'] = np.nan

In [14]:
df_missing

         Date Region Product  Sales  Quantity
0  2023-01-01  North       A    NaN        10
1  2023-01-01  North       B  150.0        15
2  2023-01-02  North       A  200.0        20
3  2023-01-02  North       B  120.0        12
4  2023-01-01  South       A  130.0        13
5  2023-01-01  South       B  180.0        18
6  2023-01-02  South       A  220.0        22
7  2023-01-02  South       B  140.0        14

In [15]:
pivot_with_nan = pd.pivot_table(df_missing,values = 'Sales', index ='Region' , columns = 'Product' , aggfunc = 'mean')

In [16]:
pivot_with_nan

Product      A      B
Region
North    200.0  135.0
South    175.0  160.0

In [17]:
pivot_filled = pd.pivot_table(df_missing,values = 'Sales',index = 'Region',columns = 'Product',aggfunc = 'mean',fill_value = 0)

In [18]:
pivot_filled

Product      A      B
Region
North    200.0  135.0
South    175.0  160.0

In [19]:
pivot_dropna = pd.pivot_table(df_missing,values = 'Sales',index = 'Region',columns = 'Product',aggfunc = 'mean',dropna = True)

In [20]:
pivot_dropna

Product      A      B
Region
North    200.0  135.0
South    175.0  160.0

In [21]:
pivot_margin = pd.pivot_table(df,values = 'Sales',index = 'Region' , columns = 'Product', aggfunc = 'sum', margins = True, margins_name = 'Total')

In [22]:
pivot_margin

Product    A    B  Total
Region
North    300  270    570
South    350  320    670
Total    650  590   1240